spring:
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpirationTime: ${JWT_ACCESS_TOKEN_EXPIRED_IN_MS}
    refreshTokenExpirationTime: ${JWT_REFRESH_TOKEN_EXPIRED_IN_MS}
  config:
    additional-location: classpath:/

server:
  port: 8081

app:
  frontend-url: ${APP_FRONTEND_PRODUCTION_BASE_URL}
  supported-http-methods:
    -GET
    -POST
    -PUT
    -PATCH
    -DELETE
    -OPTIONS
    -HEAD
  jwt:
    reset-password-token-secret-key: ${JWT_RESET_PASSWORD_SECRET_KEY}
    reset-token-expiration-in-ms: ${JWT_RESET_PASSWORD_TOKEN_EXPIRED_IN_MS}
    signup-user-verification-token-secret-key: ${JWT_SIGNUP_USER_VERIFICATION_TOKEN_SECRET_KEY}
    signup-user-verification-token-expiration-in-ms: ${JWT_SIGNUP_USER_VERIFICATION_TOKEN_EXPIRED_IN_MS}