spring:
  application:
    name: TaskBuddy
  jpa:
    show-sql: true
  config:
    additional-location: classpath:/
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  profiles:
    active: prod