spring:
  application:
    name: TaskBuddy
  jpa:
    show-sql: true
  config:
    additional-location: classpath:/
  profiles:
    active: dev

app:
  supported-http-methods:
    -GET
    -POST
    -PUT
    -PATCH
    -DELETE
    -OPTIONS
